// Generated by CoffeeScript 1.10.0
(function() {
  $(window).load(function() {
    return app.initialize();
  });

  window.app = {
    initialize: function() {
      this.w = $(window).width();
      this.h = $(window).height();
      this.hw = $('.header_wrapper').height();
      this.judgeSp();
      this.introAnim();
      return this.particleBox();
    },
    judgeSp: function() {
      if ($(window).width() <= 800) {
        this.spHeight();
        return this.risizeLoad();
      } else {
        this.mainLayer();
        return this.singlePage();
      }
    },
    mainLayer: function() {
      var hh;
      hh = this.h - this.hw;
      return $('.mainlayer').css({
        "height": hh + "px"
      });
    },
    risizeLoad: function() {
      return $(window).on('orientationchange', function() {
        return location.reload();
      });
    },
    spHeight: function() {
      var hh;
      hh = $('.mainlayer').height() + 40;
      return $('.header_wrapper').css({
        "bottom": "auto",
        "top": hh + "px"
      });
    },
    introAnim: function() {
      $('.section_wrapper .bg').css({
        "background-position": "center bottom"
      });
      return setTimeout((function() {
        return $('.section_wrapper .bg img').css({
          "margin-top": "0",
          "opacity": "1"
        });
      }), 2000);
    },
    singlePage: function() {
      var hh;
      hh = this.h - this.hw - $('.entry-header').height();
      return $('.single .post-thumbnail img').css({
        "max-height": hh + "px",
        "width": "auto"
      });
    },
    particleBox: function() {
      return $(window).mousemove(function(evt) {
        var cx, cy;
        cy = evt.clientY - 40;
        cx = evt.clientX + 120;
        return $('.particleBox').css({
          "opacity": "1",
          "position": "fixed",
          "top": cy + "px",
          "left": cx + "px"
        });
      });
    }
  };

}).call(this);

//# sourceMappingURL=common.js.map
